### ISSUE TITLE
Linux  ？？？

### ISSUE THREAD

**Issue by idqaq** [umeiko/MicroPython-DevTool#2]
for f in os.listdir(global_options["PC_PATH"]):
FileNotFoundError: [Errno 2] 没有那个文件或目录: '.\\'

**Comment by umeiko** [comment]
谢谢你的反馈！已开始进行Linux下的兼容性测试！请期待后续的更新~

**Comment by umeiko** [comment]
> 

linux系统下的兼容性修复已完成，谢谢～欢迎后续反馈
